service:
  name: nest-serverless-example

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: yarn
    excludeFiles: "**/*.spec.ts"
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'develop'}

functions:
  main: # The name of the lambda function
    handler: src/handler.handler # The module 'handler' is exported in the file 'src/handler'
    events:
      - http:
          method: any
          path: /{any+}
