version: 2.1
orbs:
  node: circleci/node@3.0.0
  assume-role: airswap/assume-role@0.2.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.20.2

yarn_cache: &yarn_cache
  keys:
    - node-deps-node12-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - node-deps-node12-

deploy_cache: &deploy_cache
  key: last-deploy-sha

yarn_install: &yarn_install
  name: Install Dependencies
  command: yarn install --frozen-lockfile --non-interactive

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run:
          <<: *yarn_install
      - save_cache:
          key: node-deps-node12-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
      - run:
          name: Install Serverless CLI and dependencies
          command: |
              sudo npm i -g serverless
              sudo apt-get install awscli
      - assume-role/assume-role
      - run:
          name: Deploy application
          command: |
            sls package --stage staging -p ./dist
            sls deploy --stage staging  --package ./dist
  checktest:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: check test
          command: echo "test"
      - run:
          name: script test
          command: |
            chmod +x changeChecker.sh
            source changeChecker.sh

workflows:
  sls_deploy:
    when:
      equal: [master, << pipeline.git.branch >>]
    jobs:
      - checktest