version: 2.1
orbs:
  node: circleci/node@3.0.0
  
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.20.2

jobs:
  build:
    parameters:
      aws-access-key-id:
        default: AWS_ACCESS_KEY_ID
        description: |
                  AWS access key id for IAM role. Set this to the name of
                  the environment variable you will use to hold this
                  value, i.e. AWS_ACCESS_KEY.
        type: env_var_name
      aws-secret-access-key:
        default: AWS_SECRET_ACCESS_KEY_ID
        description: |
            AWS secret key for IAM role. Set this to the name of
            the environment variable you will use to hold this
            value, i.e. $AWS_SECRET_ACCESS_KEY_ID.
        type: env_var_name
      profile-name:
          default: serverless-app-deployment
          description: Profile name to be configured.
          type: string
    <<: *defaults
  
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
              sudo npm i -g serverless
              npm install
              sudo apt-get install awscli
      - run:
          name: visibility test
          command: echo $<<parameters.aws-access-key-id>>
      - run:
          name: Configure AWS Access Key ID
          command: |
              aws configure set aws_access_key_id \
              $<<parameters.aws-access-key-id>> \
              --profile <<parameters.profile-name>>

      - run:
          name: Configure AWS Secret Access Key ID
          command: |
            aws configure set aws_secret_access_key \
            $<<parameters.aws-secret-access-key>> \
            --profile <<parameters.profile-name>>

      - run:
          name: Configure AWS default region
          command: |
            aws configure set region eu-central-1 \
            --profile <<parameters.profile-name>>
      - run:
          command: |
              aws configure set role_arn arn:aws:iam::659344654752:role/app-ci-stg-deployment \
                --profile <<parameters.profile-name>>
          name: Configure AWS profile role
      - run:
          command: aws configure --profile <<parameters.profile-name>> list
          name: Show configure list 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - run:
          name: Deploy application
          command: |
            chmod +x assume-role.sh
            source assume-role.sh
            sls deploy --stage staging

workflows:
  sls_deploy:
    jobs:
      - build