version: 2.1
orbs:
  node: circleci/node@3.0.0
  assume-role: airswap/assume-role@0.2.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.20.2

set_env: &set_env
  name: Setup Environment Variables
  command: |
    if [[ $CIRCLE_PULL_REQUEST ]]
    then
      echo 'Fetching Base Commit from GitHub'
      echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
      source $BASH_ENV
      echo "export CIRCLE_PR_BASE_SHA=`curl -s https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER} | jq -r '.base.sha'`" >> $BASH_ENV
      echo 'export AFFECTED_ARGS="--base ${CIRCLE_PR_BASE_SHA}"' >> $BASH_ENV
    else
      echo 'Fetching Base Commit from Deploy Cache'
      if [[ ! -f dist/last-deploy.txt ]]
      then
        mkdir dist && git rev-parse HEAD~1 > dist/last-deploy.txt
      fi
      echo 'export AFFECTED_ARGS="--base $(cat dist/last-deploy.txt)"' >> $BASH_ENV
    fi
    source $BASH_ENV
    echo $AFFECTED_ARGS

yarn_cache: &yarn_cache
  keys:
    - node-deps-node12-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - node-deps-node12-

deploy_cache: &deploy_cache
  key: last-deploy-sha

yarn_install: &yarn_install
  name: Install Dependencies
  command: yarn install --frozen-lockfile --non-interactive

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run:
          <<: *yarn_install
      - save_cache:
          key: node-deps-node12-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
      - run:
          name: Install Serverless CLI and dependencies
          command: |
              sudo npm i -g serverless
              sudo apt-get install awscli
      - assume-role/assume-role
      - run:
          name: Deploy application
          command: |
            sls package --stage staging -p ./dist
            sls deploy --stage staging  --package ./dist
  prechecktest:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: check test
          command: echo "test"
      - run:
          <<: *set_env
      - run: ls -a
      - run: cp package.json dist
      - run: ls -a
      - run: 
          name: PAPA
          command: | 
            cd dist
            ls -a
      - run:
          name: script test
          command: |
            chmod +x changeChecker.sh
            source changeChecker.sh
      - save_cache:
          key: build-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - dist/package.json
      - store_artifacts:
          path: dist
  checktest:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - restore_cache:
          key: papa-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run: ls -a
      - run: 
          name: distt
          command: | 
            cd dist
            ls -a
      - run: 
          name: PAPA
          command: | 
            cd dist/papa
            ls -a
workflows:
  sls_deploy:
    # when:
    #   equal: [master, << pipeline.git.branch >>]
    jobs:
      - prechecktest
      - checktest:
          requires:
            - prechecktest
